bucket={
    'access-key-id':'AKIAU2BGNYTKSS2DNLVB',
    'secret-access-key':'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',
    'region':'us-east-2'
}
rekog={
    'access-key-id':'AKIAU2BGNYTKUH3LAR7N',
    'secret-access-key':'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',
    'region':'us-east-2'
}