version: '3'

services: 
    db:
        image: mongo:latest
        container_name: mongodb
        ports:
            - "27017-27019:27017-27019"
        volumes: 
            - database:/data/db


volumes:
    database: